name: build and test

on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies
      run: dotnet restore ./Otus.Teaching.PromoCodeFactory.WebHost/Otus.Teaching.PromoCodeFactory.WebHost.csproj
      working-directory: src

    - name: Build the solution
      run: dotnet build --no-restore ./Otus.Teaching.PromoCodeFactory.WebHost/Otus.Teaching.PromoCodeFactory.WebHost.csproj
      working-directory: src

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: src
